# Generated by Django 2.2.16 on 2022-06-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220617_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin'), ('AnonymousUser', 'AnonymousUser')], default='user', max_length=16, verbose_name='Пользовательская роль'),
        ),
    ]
