# Generated by Django 2.2.16 on 2022-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
